apiVersion: v1
kind: ConfigMap
metadata:
  name: oracle-rdbms-config
  labels:
    app: oracle-rdbms-orclcbd
data:
  ORACLE_CHARACTERSET: "AL32UTF8"
  ORACLE_EDITION: "enterprise"
  ORACLE_SID: "ORCLCDB"
  ORACLE_PDB: "ORCLPDB1"
