apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-rdbms-orclcdb
  labels:
    app: oracle-rdbms-orclcdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle-rdbms-orclcdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: oracle-rdbms-orclcdb
    spec:
      securityContext:
        runAsUser: 54321
        fsGroup: 54321
      containers:
        - name: rdbms
          image: itunified/oracle-database-ee:latest
          envFrom:
            - configMapRef:
                name: oracle-rdbms-config
            - secretRef:
                name: oracle-rdbms-credentials
          ports:
            - containerPort: 1521
              name: oracle-listener
            - containerPort: 5500
              name: oem-express
          volumeMounts:
            - name: oradata
              mountPath: /opt/oracle/oradata
          readinessProbe:
            initialDelaySeconds: 60
            periodSeconds: 60
            exec:
              command:
                - /bin/sh
                - "-c"
                - $ORACLE_BASE/$CHECK_DB_FILE
          livenessProbe:
            initialDelaySeconds: 300
            periodSeconds: 60
            exec:
              command:
                - /bin/sh
                - "-c"
                - $ORACLE_BASE/$CHECK_DB_FILE
      imagePullSecrets:
        - name: docker-hub-cred
      volumes:
        - name: oradata
          persistentVolumeClaim:
            claimName: oracle-rdbms-oradata
