apiVersion: v1
kind: PersistentVolume
metadata:
  name: oracle-rdbms-oradata
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/oracle/oradata
