apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-database
  labels:
    app: oracle-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle-database
  template:
    metadata:
      labels:
        app: oracle-database
    spec:
      containers:
        - name: oracle-database
          image: itunified/oracle-database-ee:latest
          ports:
            - containerPort: 1521
          volumeMounts:
            - mountPath: /opt/oracle/oradata
              name: oracle-storage
      imagePullSecrets:
        - name: docker-hub-cred
      volumes:
        - name: oracle-storage
          persistentVolumeClaim:
            claimName: oracle-pvc
