apiVersion: v1
kind: PersistentVolume
metadata:
  name: oracle-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
<<<<<<< HEAD
    path: /opt/oracle/oradata
=======
    path: /u01/app/oracle/oradata
>>>>>>> refs/remotes/origin/main
