apiVersion: v1
kind: Service
metadata:
  name: oracle-database-service
  labels:
    app: oracle-database
spec:
  type: NodePort
  selector:
    app: oracle-database
  ports:
    - protocol: TCP
      port: 1521
      targetPort: 1521
      nodePort: 31521 # Ein zufällig gewählter Port innerhalb des NodePort-Bereichs (30000-32767)

